version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BookStoreLive
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./Backend/BookStore-ba/BookStore
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysqldb:3306/BookStoreLive
      DB_USERNAME: root
      DB_PASSWORD: root
      CORS_ALLOWED_ORIGINS: http://localhost:5173 # Allow frontend origin
    depends_on:
      - mysqldb

  frontend:
    build: ./BookStore-fr
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:8080
    depends_on:
      - backend

volumes:
  db_data:
